#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
alignment = 'left'
type = 'prompt'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'blue'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'green'
template = ' {{ .HEAD }}{{ if gt .StashCount 0 }} *{{ .StashCount }}{{ end }}'

[blocks.segments.properties]
branch_icon = ''
fetch_status = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
background = 'transparent'
foreground = 'green'
foreground_templates = [
	'{{if gt .Code 0}}red{{end}}',
	'{{if eq .Code 0}}green{{end}}',
]
template = '❯'

[transient_prompt]
foreground = 'magenta'
foreground_templates = [
	'{{if gt .Code 0}}red{{end}}',
	'{{if eq .Code 0}}green{{end}}',
]
background = 'transparent'
template = '❯ '

#
# [[blocks]]
#   type = 'rprompt'
#
#   [[blocks.segments]]
#     type = 'time'
#     style = 'plain'
#     foreground = '#00C5C7'
#     template = ' {{ .CurrentDate | date .Format }} '
#
#     [blocks.segments.properties]
#       time_format = '15:04:05'
#
# [[blocks]]
#   type = 'prompt'
#   alignment = 'left'
#
#   [[blocks.segments]]
#     type = 'path'
#     style = 'plain'
#     foreground = '#77E4F7'
#     template = '{{ .Path }} '
#
#     [blocks.segments.properties]
#       style = 'full'
#
#   [[blocks.segments]]
#     type = 'git'
#     style = 'plain'
#     foreground = '#FFE700'
#     template = '{{ .HEAD }} '
#
#   [[blocks.segments]]
#     type = 'text'
#     style = 'plain'
#     foreground = '#43D426'
#     template = '❯ '
