[tools]
python = ['3.12.4']
node = "24"
ruby = ['3.3.5']
usage = "latest"
uv = "latest"
bun = "latest"
deno = "latest"
pnpm = "latest"
erlang = "latest"
elixir = "latest"
typst = "latest"
go = "1.25"

[settings]
idiomatic_version_file_enable_tools = ["python"]
